### ISSUE TITLE
Release v0.3.4 has a version string of v0.3.3.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb-light-client#174]
The binaries from the v0.3.4 release are reporting that they are v0.3.3.

```bash
$ ./ckb-light-client -V
CKB Light Client 0.3.3
```

https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.3.4

**Comment by quake** [comment]
sorry, I made a mistake, should you try to re-download the binary, it has been resolved now.

**Comment by jordanmack** [comment]
Issue is fixed.
